filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//src:__pkg__"],
)

java_test(
    name = "tikv_meta_test",
    srcs = glob(["*.java"]),
    test_class = "DBInfoTest",
    deps = [
    ],
)